"""initial migration

Revision ID: 8f7a286f13b9
Revises: 
Create Date: 2026-05-26 16:31:04.933101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7a286f13b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.drop_constraint('unique_phone', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('unique_phone', 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    # ### end Alembic commands ###
